#!/usr/bin/env python3
"""Mirror the PRODUCTION database's table structure into the DEV database.

Why: Replit's Publish compares the dev DB (helium) to production and generates
migrations that make production match dev. Tables/columns that exist only in
production (the revenue hub + MFF tables our pipelines create directly in the
report Neon) show up as "You're about to delete <table>" — approving that wipes
the live dashboards. Running this first makes dev structurally match production,
so Publish has nothing to drop.

Safety:
  * Reads production only (read-only session). Never writes to production.
  * Copies STRUCTURE only — tables, columns, defaults, keys, indexes. No rows.
  * Additive only on dev: creates missing tables / adds missing columns. Never
    drops or alters anything that already exists.
  * Refuses to run if dev and production are the same database.

Usage (Replit Shell, from the repo root):
    python3 mmm-pipeline-package/scripts/mirror_prod_schema_to_dev.py            # apply
    python3 mmm-pipeline-package/scripts/mirror_prod_schema_to_dev.py --dry-run  # show only

Env: NEON_DATABASE_URL = production (report Neon), DATABASE_URL = dev (helium).
"""
import os
import re
import sys
from urllib.parse import urlparse

import psycopg2

SCHEMA = "public"


def _ident(url):
    u = urlparse(url)
    return (u.hostname or "", u.port or 5432, (u.path or "").lstrip("/"))


def q(ident):
    return '"' + ident.replace('"', '""') + '"'


def tables(cur):
    cur.execute(
        "select table_name from information_schema.tables "
        "where table_schema=%s and table_type='BASE TABLE'",
        (SCHEMA,),
    )
    return {r[0] for r in cur.fetchall()}


def columns(cur, table):
    cur.execute(
        """
        select a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull,
               pg_get_expr(d.adbin, d.adrelid), a.attidentity
          from pg_attribute a
          left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
         where a.attrelid = %s::regclass and a.attnum > 0 and not a.attisdropped
         order by a.attnum
        """,
        (f"{SCHEMA}.{q(table)}",),
    )
    return cur.fetchall()


def column_sql(name, typ, notnull, default, identity):
    parts = [q(name), typ]
    if identity == "a":
        parts.append("generated always as identity")
    elif identity == "d":
        parts.append("generated by default as identity")
    elif default is not None:
        parts.append(f"default {default}")
    if notnull:
        parts.append("not null")
    return " ".join(parts)


def sequences_in(default):
    return re.findall(r"nextval\('([^']+)'", default or "")


def constraints(cur, table):
    cur.execute(
        "select conname, contype, pg_get_constraintdef(oid) from pg_constraint "
        "where conrelid = %s::regclass order by contype",
        (f"{SCHEMA}.{q(table)}",),
    )
    return cur.fetchall()


def indexes(cur, table):
    # Plain indexes only; ones backing a PK/UNIQUE constraint come with it.
    cur.execute(
        """
        select i.indexdef from pg_indexes i
         where i.schemaname = %s and i.tablename = %s
           and not exists (select 1 from pg_constraint c
                            where c.conindid = (quote_ident(i.schemaname)||'.'||quote_ident(i.indexname))::regclass)
        """,
        (SCHEMA, table),
    )
    return [re.sub(r"^CREATE (UNIQUE )?INDEX ", r"CREATE \1INDEX IF NOT EXISTS ", r[0]) for r in cur.fetchall()]


def main():
    dry = "--dry-run" in sys.argv
    prod_url = os.environ.get("NEON_DATABASE_URL")
    dev_url = os.environ.get("DATABASE_URL")
    if not prod_url or not dev_url:
        sys.exit("Need NEON_DATABASE_URL (production) and DATABASE_URL (dev).")
    if _ident(prod_url) == _ident(dev_url):
        sys.exit("DATABASE_URL points at production — nothing to mirror (this is only for the dev DB).")

    prod = psycopg2.connect(prod_url)
    prod.set_session(readonly=True)
    dev = psycopg2.connect(dev_url)
    pc, dc = prod.cursor(), dev.cursor()

    prod_tables, dev_tables = tables(pc), tables(dc)
    stmts, deferred_fks = [], []

    for t in sorted(prod_tables - dev_tables):
        cols = columns(pc, t)
        for _, _, _, default, _ in cols:
            for seq in sequences_in(default):
                stmts.append(f"create sequence if not exists {seq}")
        body = [column_sql(*c) for c in cols]
        for name, kind, definition in constraints(pc, t):
            if kind == "f":
                deferred_fks.append(f"alter table {q(t)} add constraint {q(name)} {definition}")
            elif kind in ("p", "u", "c", "x"):
                body.append(f"constraint {q(name)} {definition}")
        stmts.append(f"create table if not exists {q(t)} (\n  " + ",\n  ".join(body) + "\n)")
        stmts.extend(indexes(pc, t))

    for t in sorted(prod_tables & dev_tables):
        have = {c[0] for c in columns(dc, t)}
        for c in columns(pc, t):
            if c[0] not in have:
                # Added columns can't be NOT NULL without a default on a table with rows.
                name, typ, notnull, default, identity = c
                safe_notnull = notnull and (default is not None or identity)
                for seq in sequences_in(default):
                    stmts.append(f"create sequence if not exists {seq}")
                stmts.append(
                    f"alter table {q(t)} add column if not exists "
                    + column_sql(name, typ, safe_notnull, default, identity)
                )

    stmts.extend(deferred_fks)

    if not stmts:
        print("Dev already matches production's structure — nothing to do. Safe to Publish.")
        return

    missing = sorted(prod_tables - dev_tables)
    print(f"Production tables missing in dev: {len(missing)}")
    for t in missing:
        print(f"  + {t}")
    for s in stmts:
        print(("-- would run: " if dry else "-- ") + s.splitlines()[0][:110])
    if dry:
        print("Dry run — nothing changed.")
        return
    for s in stmts:
        dc.execute(s)
    dev.commit()
    print(f"Done. Applied {len(stmts)} statement(s) to dev. Now Publish — it should no longer offer to delete these tables.")


if __name__ == "__main__":
    main()
