import { useState, useEffect, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { OfferCard } from "@/components/admin/offer-card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel } from "@/components/ui/form";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { insertOfferSchema } from "@shared/schema";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Plus, Upload, Filter } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { z } from "zod";

const createOfferFormSchema = insertOfferSchema.extend({
  displayPages: z.array(z.number()).optional(),
  questionIds: z.array(z.string()).optional(),
});

type CreateOfferForm = z.infer<typeof createOfferFormSchema>;

export default function Offers() {
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [editingOffer, setEditingOffer] = useState<any>(null);
  const [filters, setFilters] = useState({
    category: 'all',
    status: 'all',
    search: '',
  });

  const { toast } = useToast();
  const queryClient = useQueryClient();
  
  // Track the last auto-generated impression pixel to avoid overwriting manual edits
  const lastAutoGeneratedPixel = useRef<string>('');

  const { data: offers, isLoading } = useQuery({
    queryKey: ['/api/offers'],
  });

  const { data: questions } = useQuery<any[]>({
    queryKey: ['/api/questions'],
  });

  const createOfferMutation = useMutation({
    mutationFn: async (data: CreateOfferForm) => {
      await apiRequest('POST', '/api/offers', data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/offers'] });
      handleModalChange(false); // This will close modal and reset form
      toast({
        title: "Success",
        description: "Offer created successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const updateOfferMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<CreateOfferForm> }) => {
      await apiRequest('PUT', `/api/offers/${id}`, data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/offers'] });
      handleEditModalClose();
      toast({
        title: "Success",
        description: "Offer updated successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const form = useForm<CreateOfferForm>({
    resolver: zodResolver(createOfferFormSchema),
    defaultValues: {
      name: '',
      description: '',
      payout: '0.00',
      category: '',
      offerType: 'tune_standard',
      tuneOfferId: '',
      clickUrl: '',
      impressionPixel: '',
      imageUrl: '',
      scriptContent: '',
      linkText: 'Next',
      triggerSettings: null,
      displayPages: [],
      questionIds: [],
      position: 1,
      isActive: true,
      isPaused: false,
    },
  });

  const selectedOfferType = form.watch('offerType');
  const clickUrl = form.watch('clickUrl');

  // Auto-generate impression pixel from Tune click URL
  useEffect(() => {
    if (!clickUrl) {
      // Click URL cleared - clear auto-generated pixel too
      const currentImpressionPixel = form.getValues('impressionPixel');
      if (currentImpressionPixel === lastAutoGeneratedPixel.current) {
        form.setValue('impressionPixel', '', { shouldDirty: false, shouldTouch: false });
      }
      lastAutoGeneratedPixel.current = '';
      return;
    }
    
    // Check if this is a Tune/HasOffers click URL (contains /aff_c path)
    if (clickUrl.includes('/aff_c')) {
      // Transform click URL to impression pixel URL by replacing /aff_c with /aff_i
      let impressionUrl = clickUrl.replace('/aff_c', '/aff_i');
      
      // Add cachebuster parameter to prevent browser caching
      const separator = impressionUrl.includes('?') ? '&' : '?';
      impressionUrl += `${separator}cb=[CACHEBUSTER]`;
      
      const currentImpressionPixel = form.getValues('impressionPixel');
      
      // Only auto-populate if:
      // 1. Field is empty, OR
      // 2. Current value matches the last auto-generated value (user hasn't manually edited)
      if (!currentImpressionPixel || currentImpressionPixel === lastAutoGeneratedPixel.current) {
        // Only set if value is actually different to avoid unnecessary dirty state
        if (currentImpressionPixel !== impressionUrl) {
          form.setValue('impressionPixel', impressionUrl, { shouldDirty: false, shouldTouch: false });
        }
        lastAutoGeneratedPixel.current = impressionUrl;
      }
    } else {
      // Not a Tune URL anymore - clear the auto-generated pixel if present
      const currentImpressionPixel = form.getValues('impressionPixel');
      if (currentImpressionPixel === lastAutoGeneratedPixel.current) {
        // Only clear if it was auto-generated (matches last known auto-value)
        form.setValue('impressionPixel', '', { shouldDirty: false, shouldTouch: false });
      }
      // Clear tracking so future Tune URLs can be auto-managed
      lastAutoGeneratedPixel.current = '';
    }
  }, [clickUrl, form]);

  const onSubmit = (data: CreateOfferForm) => {
    createOfferMutation.mutate(data);
  };

  // Reset form when modal opens/closes to prevent stale data
  const handleModalChange = (open: boolean) => {
    setShowCreateModal(open);
    lastAutoGeneratedPixel.current = ''; // Reset auto-gen tracker
    // Always reset form to ensure clean state
    form.reset({
      name: '',
      description: '',
      payout: '0.00',
      category: '',
      offerType: 'tune_standard',
      tuneOfferId: '',
      clickUrl: '',
      impressionPixel: '',
      imageUrl: '',
      scriptContent: '',
      linkText: 'Next',
      triggerSettings: null,
      displayPages: [],
      questionIds: [],
      position: 1,
      isActive: true,
      isPaused: false,
    });
  };

  const handleEdit = (offer: any) => {
    setEditingOffer(offer);
    
    // Smart detection: Check if existing pixel appears to be auto-generated
    // If click URL is a Tune URL and pixel matches the derived format, mark it as auto-generated
    // Otherwise, leave ref empty to preserve manual customizations
    if (offer.clickUrl && offer.clickUrl.includes('/aff_c')) {
      let derivedPixel = offer.clickUrl.replace('/aff_c', '/aff_i');
      const separator = derivedPixel.includes('?') ? '&' : '?';
      derivedPixel += `${separator}cb=[CACHEBUSTER]`;
      
      if (offer.impressionPixel === derivedPixel) {
        // Existing pixel matches auto-generated format, so we can manage it
        lastAutoGeneratedPixel.current = derivedPixel;
      } else {
        // Pixel has been manually customized (different from derived), preserve it
        lastAutoGeneratedPixel.current = '';
      }
    } else {
      lastAutoGeneratedPixel.current = '';
    }
    
    // Pre-fill form with offer data
    form.reset({
      name: offer.name,
      description: offer.description || '',
      payout: offer.payout,
      category: offer.category,
      offerType: offer.offerType || 'tune_standard',
      tuneOfferId: offer.tuneOfferId || '',
      clickUrl: offer.clickUrl || '',
      impressionPixel: offer.impressionPixel || '',
      imageUrl: offer.imageUrl || '',
      scriptContent: offer.scriptContent || '',
      linkText: offer.linkText || 'Next',
      triggerSettings: offer.triggerSettings || null,
      displayPages: offer.displayPages || [],
      questionIds: offer.questionIds || [],
      position: offer.position || 1,
      isActive: offer.isActive,
      isPaused: offer.isPaused,
    });
    setShowEditModal(true);
  };

  const handleEditModalClose = () => {
    setShowEditModal(false);
    setEditingOffer(null);
    lastAutoGeneratedPixel.current = ''; // Reset auto-gen tracker
    form.reset({
      name: '',
      description: '',
      payout: '0.00',
      category: '',
      offerType: 'tune_standard',
      tuneOfferId: '',
      clickUrl: '',
      impressionPixel: '',
      imageUrl: '',
      scriptContent: '',
      linkText: 'Next',
      triggerSettings: null,
      displayPages: [],
      questionIds: [],
      position: 1,
      isActive: true,
      isPaused: false,
    });
  };

  const onEditSubmit = (data: CreateOfferForm) => {
    if (editingOffer) {
      updateOfferMutation.mutate({ id: editingOffer.id, data });
    }
  };

  const offersArray = Array.isArray(offers) ? offers : [];
  const filteredOffers = offersArray.filter((offer: any) => {
    if (filters.category && filters.category !== 'all' && offer.category !== filters.category) return false;
    if (filters.status === 'active' && (!offer.isActive || offer.isPaused)) return false;
    if (filters.status === 'paused' && !offer.isPaused) return false;
    if (filters.status === 'inactive' && offer.isActive) return false;
    if (filters.search && !offer.name.toLowerCase().includes(filters.search.toLowerCase())) return false;
    return true;
  });

  return (
    <div className="p-6 space-y-6" data-testid="offers-page">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Offers Management</h2>
          <p className="text-muted-foreground">Manage and configure co-registration offers</p>
        </div>
        <div className="flex space-x-3">
          <Button variant="secondary" data-testid="button-import">
            <Upload className="h-4 w-4 mr-2" />
            Import CSV
          </Button>
          <Button 
            onClick={() => handleModalChange(true)}
            data-testid="button-create-offer"
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Offer
          </Button>
        </div>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="p-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label className="block text-sm font-medium mb-2">Category</label>
              <Select value={filters.category} onValueChange={(value) => setFilters(prev => ({ ...prev, category: value }))}>
                <SelectTrigger data-testid="select-category">
                  <SelectValue placeholder="All Categories" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Categories</SelectItem>
                  <SelectItem value="financial">Financial Services</SelectItem>
                  <SelectItem value="health">Health & Wellness</SelectItem>
                  <SelectItem value="shopping">Shopping</SelectItem>
                  <SelectItem value="travel">Travel</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Status</label>
              <Select value={filters.status} onValueChange={(value) => setFilters(prev => ({ ...prev, status: value }))}>
                <SelectTrigger data-testid="select-status">
                  <SelectValue placeholder="All Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="paused">Paused</SelectItem>
                  <SelectItem value="inactive">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Payout Range</label>
              <Select>
                <SelectTrigger data-testid="select-payout">
                  <SelectValue placeholder="All Payouts" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Payouts</SelectItem>
                  <SelectItem value="0-1">$0 - $1</SelectItem>
                  <SelectItem value="1-3">$1 - $3</SelectItem>
                  <SelectItem value="3-5">$3 - $5</SelectItem>
                  <SelectItem value="5+">$5+</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Search</label>
              <Input
                placeholder="Search offers..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({ ...prev, search: e.target.value }))}
                data-testid="input-search"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Offers Grid */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="h-64 bg-muted animate-pulse rounded-lg" />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredOffers.map((offer: any) => (
            <OfferCard key={offer.id} offer={offer} onEdit={handleEdit} />
          ))}
          
          {filteredOffers.length === 0 && (
            <div className="col-span-full text-center py-12">
              <Filter className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
              <p className="text-lg text-muted-foreground">No offers found</p>
              <p className="text-sm text-muted-foreground">Try adjusting your filters</p>
            </div>
          )}
        </div>
      )}

      {/* Create Offer Modal */}
      <Dialog open={showCreateModal} onOpenChange={handleModalChange}>
        <DialogContent className="max-w-2xl" data-testid="modal-create-offer">
          <DialogHeader>
            <DialogTitle>Add New Offer</DialogTitle>
          </DialogHeader>
          
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              {/* Offer Type Selector */}
              <FormField
                control={form.control}
                name="offerType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Offer Type *</FormLabel>
                    <FormControl>
                      <Select value={field.value || 'tune_standard'} onValueChange={field.onChange}>
                        <SelectTrigger data-testid="select-offer-type">
                          <SelectValue placeholder="Select Offer Type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="tune_standard">Tune Standard (Tracking Link + Pixel)</SelectItem>
                          <SelectItem value="popup_script">Popup Script</SelectItem>
                          <SelectItem value="next_link">Next Link (Coreg)</SelectItem>
                        </SelectContent>
                      </Select>
                    </FormControl>
                  </FormItem>
                )}
              />

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Tune Offer ID - only for tune_standard */}
                {selectedOfferType === 'tune_standard' && (
                  <FormField
                    control={form.control}
                    name="tuneOfferId"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Tune Offer ID</FormLabel>
                        <FormControl>
                          <Input placeholder="12345" {...field} value={field.value || ''} data-testid="input-tune-id" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                )}
                
                <FormField
                  control={form.control}
                  name="payout"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Payout Amount *</FormLabel>
                      <FormControl>
                        <div className="flex items-center">
                          <span className="mr-2">$</span>
                          <Input
                            type="number"
                            step="0.01"
                            placeholder="2.50"
                            {...field}
                            data-testid="input-payout"
                          />
                        </div>
                      </FormControl>
                    </FormItem>
                  )}
                />
              </div>
              
              <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Offer Name *</FormLabel>
                    <FormControl>
                      <Input placeholder="Insurance Quote" {...field} data-testid="input-name" />
                    </FormControl>
                  </FormItem>
                )}
              />
              
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description (Optional)</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Enter offer description (optional)..." 
                        {...field} 
                        value={field.value ?? ''} 
                        onChange={(e) => field.onChange(e.target.value || null)}
                        data-testid="textarea-description" 
                      />
                    </FormControl>
                    <p className="text-xs text-muted-foreground">Leave blank if you don't need a description</p>
                  </FormItem>
                )}
              />
              
              <FormField
                control={form.control}
                name="category"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Category *</FormLabel>
                    <FormControl>
                      <Select value={field.value || ''} onValueChange={field.onChange}>
                        <SelectTrigger data-testid="select-form-category">
                          <SelectValue placeholder="Select Category" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="financial">Financial Services</SelectItem>
                          <SelectItem value="health">Health & Wellness</SelectItem>
                          <SelectItem value="shopping">Shopping</SelectItem>
                          <SelectItem value="travel">Travel</SelectItem>
                          <SelectItem value="education">Education</SelectItem>
                        </SelectContent>
                      </Select>
                    </FormControl>
                  </FormItem>
                )}
              />

              {/* Tune Standard Offer Fields */}
              {selectedOfferType === 'tune_standard' && (
                <>
                  <FormField
                    control={form.control}
                    name="clickUrl"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Tracking Link (Click URL) *</FormLabel>
                        <FormControl>
                          <Input placeholder="https://track.affiliate.com/..." {...field} value={field.value || ''} data-testid="input-click-url" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="impressionPixel"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Impression Pixel URL</FormLabel>
                        <FormControl>
                          <Input placeholder="https://track.affiliate.com/pixel..." {...field} value={field.value || ''} data-testid="input-impression-pixel" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="imageUrl"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Offer Image URL</FormLabel>
                        <FormControl>
                          <Input placeholder="https://cdn.example.com/offer-image.jpg" {...field} value={field.value || ''} data-testid="input-image-url" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </>
              )}

              {/* Popup Script Offer Fields */}
              {selectedOfferType === 'popup_script' && (
                <FormField
                  control={form.control}
                  name="scriptContent"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Popup Script *</FormLabel>
                      <FormControl>
                        <Textarea 
                          placeholder="<script>...</script>" 
                          {...field}
                          value={field.value || ''}
                          className="font-mono text-sm min-h-[120px]"
                          data-testid="textarea-script-content"
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
              )}

              {/* Next Link Offer Fields */}
              {selectedOfferType === 'next_link' && (
                <>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="linkText"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Link Text *</FormLabel>
                          <FormControl>
                            <Input placeholder="Next" {...field} value={field.value || ''} data-testid="input-link-text" />
                          </FormControl>
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name="clickUrl"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Coreg Script URL *</FormLabel>
                          <FormControl>
                            <Input placeholder="https://coreg.example.com/script" {...field} value={field.value || ''} data-testid="input-coreg-url" />
                          </FormControl>
                        </FormItem>
                      )}
                    />
                  </div>
                </>
              )}
              
              <div>
                <FormLabel>Page Display (One-Time Pages)</FormLabel>
                <p className="text-sm text-muted-foreground mb-2">
                  Select where to show this offer. These are single pages, NOT survey questions.
                </p>
                <div className="space-y-2 mt-3">
                  {[
                    { value: 5, label: 'Registration Page', desc: 'Shows once during registration' },
                    { value: 15, label: 'Main Offers Page', desc: 'Shows once after all survey questions' },
                    { value: 20, label: 'Exit Lottery Page', desc: 'Shows once at the very end' }
                  ].map((page) => (
                    <label key={page.value} className="flex items-start gap-2 cursor-pointer">
                      <Checkbox
                        checked={form.watch('displayPages')?.includes(page.value)}
                        onCheckedChange={(checked) => {
                          const current = form.getValues('displayPages') || [];
                          if (checked) {
                            form.setValue('displayPages', [...current, page.value]);
                          } else {
                            form.setValue('displayPages', current.filter(p => p !== page.value));
                          }
                        }}
                        data-testid={`checkbox-page-${page.value}`}
                        className="mt-1"
                      />
                      <div>
                        <div className="font-medium">{page.label}</div>
                        <div className="text-xs text-muted-foreground">{page.desc}</div>
                      </div>
                    </label>
                  ))}
                </div>
                <p className="text-xs text-amber-600 dark:text-amber-400 mt-3 p-2 bg-amber-50 dark:bg-amber-900/20 rounded">
                  ⚠️ For survey questions, use "Question Display" section below - NOT this section
                </p>
              </div>

              <div>
                <FormLabel>Question Display</FormLabel>
                <p className="text-sm text-muted-foreground mb-2">
                  Show this offer after specific questions (overrides page-based targeting)
                </p>
                <div className="grid grid-cols-2 gap-2 mt-2 max-h-48 overflow-y-auto border rounded p-2">
                  {questions && questions.length > 0 ? (
                    questions.map((question: any) => (
                      <label key={question.id} className="flex items-start gap-2">
                        <Checkbox
                          checked={form.watch('questionIds')?.includes(question.id)}
                          onCheckedChange={(checked) => {
                            const current = form.getValues('questionIds') || [];
                            if (checked) {
                              form.setValue('questionIds', [...current, question.id]);
                            } else {
                              form.setValue('questionIds', current.filter((id: string) => id !== question.id));
                            }
                          }}
                          data-testid={`checkbox-question-${question.id}`}
                        />
                        <span className="text-sm">Q{question.orderIndex + 1}: {question.text.substring(0, 50)}{question.text.length > 50 ? '...' : ''}</span>
                      </label>
                    ))
                  ) : (
                    <p className="text-sm text-muted-foreground col-span-2">No active questions available</p>
                  )}
                </div>
              </div>
              
              <div className="flex justify-end space-x-3 mt-6">
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() => handleModalChange(false)}
                  data-testid="button-cancel"
                >
                  Cancel
                </Button>
                <Button 
                  type="submit" 
                  disabled={createOfferMutation.isPending}
                  data-testid="button-create"
                >
                  {createOfferMutation.isPending ? 'Creating...' : 'Create Offer'}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>

      {/* Edit Offer Modal */}
      <Dialog open={showEditModal} onOpenChange={handleEditModalClose}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto" data-testid="modal-edit-offer">
          <DialogHeader>
            <DialogTitle>Edit Offer</DialogTitle>
          </DialogHeader>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onEditSubmit)} className="space-y-4">
              {/* Use editingOffer for conditional rendering in edit mode */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Offer Name *</FormLabel>
                      <FormControl>
                        <Input placeholder="Premium Insurance Offer" {...field} data-testid="input-offer-name" />
                      </FormControl>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="payout"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Payout *</FormLabel>
                      <FormControl>
                        <Input type="number" step="0.01" placeholder="2.50" {...field} data-testid="input-payout" />
                      </FormControl>
                    </FormItem>
                  )}
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="category"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Category *</FormLabel>
                      <FormControl>
                        <Input placeholder="Financial Services" {...field} data-testid="input-category" />
                      </FormControl>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="offerType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Offer Type *</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value} data-testid="select-offer-type">
                        <SelectTrigger>
                          <SelectValue placeholder="Select offer type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="tune_standard">Tune Standard (Tracking + Pixel)</SelectItem>
                          <SelectItem value="popup_script">Popup Script</SelectItem>
                          <SelectItem value="next_link">Next Link (Coreg)</SelectItem>
                        </SelectContent>
                      </Select>
                    </FormItem>
                  )}
                />
              </div>
              
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description (Optional)</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Enter offer description (optional)..." 
                        {...field} 
                        value={field.value ?? ''} 
                        onChange={(e) => field.onChange(e.target.value || null)}
                        data-testid="textarea-description" 
                      />
                    </FormControl>
                    <p className="text-xs text-muted-foreground">Leave blank if you don't need a description</p>
                  </FormItem>
                )}
              />
              
              {/* Show all fields in edit modal */}
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="tuneOfferId"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Tune Offer ID</FormLabel>
                        <FormControl>
                          <Input placeholder="TUNE-12345" {...field} value={field.value || ''} data-testid="input-tune-id" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="clickUrl"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Click/Tracking URL</FormLabel>
                        <FormControl>
                          <Input placeholder="https://track.example.com/click" {...field} value={field.value || ''} data-testid="input-click-url" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="impressionPixel"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Impression Pixel URL</FormLabel>
                        <FormControl>
                          <Input placeholder="https://track.example.com/pixel.gif" {...field} value={field.value || ''} data-testid="input-impression-pixel" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="imageUrl"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Image URL</FormLabel>
                        <FormControl>
                          <Input placeholder="https://example.com/image.jpg" {...field} value={field.value || ''} data-testid="input-image-url" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </div>
                
                <FormField
                  control={form.control}
                  name="scriptContent"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Script Content</FormLabel>
                      <FormControl>
                        <Textarea 
                          placeholder="<script>...</script>" 
                          {...field} 
                          value={field.value || ''} 
                          data-testid="textarea-script-content" 
                          className="font-mono text-sm"
                          rows={4}
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="linkText"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Link Text</FormLabel>
                        <FormControl>
                          <Input placeholder="Next" {...field} value={field.value || ''} data-testid="input-link-text" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="position"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Display Position</FormLabel>
                        <FormControl>
                          <Input type="number" placeholder="1" {...field} value={field.value || 1} data-testid="input-position" />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </div>
              </div>
              
              <FormField
                control={form.control}
                name="displayPages"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Page Display (One-Time Pages)</FormLabel>
                    <p className="text-sm text-muted-foreground mb-2">
                      Select where to show this offer. These are single pages, NOT survey questions.
                    </p>
                    <div className="space-y-2 mt-3">
                      {[
                        { value: 5, label: 'Registration Page', desc: 'Shows once during registration' },
                        { value: 15, label: 'Main Offers Page', desc: 'Shows once after all survey questions' },
                        { value: 20, label: 'Exit Lottery Page', desc: 'Shows once at the very end' }
                      ].map((page) => (
                        <label key={page.value} className="flex items-start gap-2 cursor-pointer">
                          <Checkbox
                            checked={(field.value || []).includes(page.value)}
                            onCheckedChange={(checked) => {
                              const current = field.value || [];
                              if (checked) {
                                field.onChange([...current, page.value]);
                              } else {
                                field.onChange(current.filter((p: number) => p !== page.value));
                              }
                            }}
                            data-testid={`checkbox-page-${page.value}`}
                            className="mt-1"
                          />
                          <div>
                            <div className="font-medium">{page.label}</div>
                            <div className="text-xs text-muted-foreground">{page.desc}</div>
                          </div>
                        </label>
                      ))}
                    </div>
                    <p className="text-xs text-amber-600 dark:text-amber-400 mt-3 p-2 bg-amber-50 dark:bg-amber-900/20 rounded">
                      ⚠️ For survey questions, use "Question Display" section below - NOT this section
                    </p>
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="questionIds"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Question Display</FormLabel>
                    <p className="text-sm text-muted-foreground mb-2">
                      Show this offer after specific questions (overrides page-based targeting)
                    </p>
                    <div className="grid grid-cols-2 gap-2 mt-2 max-h-48 overflow-y-auto border rounded p-2">
                      {questions && questions.length > 0 ? (
                        questions.map((question: any) => (
                          <label key={question.id} className="flex items-start gap-2">
                            <Checkbox
                              checked={(field.value || []).includes(question.id)}
                              onCheckedChange={(checked) => {
                                const current = field.value || [];
                                if (checked) {
                                  field.onChange([...current, question.id]);
                                } else {
                                  field.onChange(current.filter((id: string) => id !== question.id));
                                }
                              }}
                              data-testid={`checkbox-question-${question.id}`}
                            />
                            <span className="text-sm">Q{question.orderIndex + 1}: {question.text.substring(0, 50)}{question.text.length > 50 ? '...' : ''}</span>
                          </label>
                        ))
                      ) : (
                        <p className="text-sm text-muted-foreground col-span-2">No active questions available</p>
                      )}
                    </div>
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-3 mt-6">
                <Button
                  type="button"
                  variant="secondary"
                  onClick={handleEditModalClose}
                  data-testid="button-cancel-edit"
                >
                  Cancel
                </Button>
                <Button 
                  type="submit" 
                  disabled={updateOfferMutation.isPending}
                  data-testid="button-update"
                >
                  {updateOfferMutation.isPending ? 'Updating...' : 'Update Offer'}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
